version: 2
jobs:
    build:
        machine:
            image: ubuntu-2004:202104-01
        working_directory: ~/repo
        steps:
            - checkout
    deploy:
        machine:
            enabled: true
        steps:
            - run:
                name: Deploy to Prod
                command: |
                    - ../build/deploy.sh
