version: 2
jobs:
    #    build:
    #        machine:
    #            image: ubuntu-2004:202104-01
    #        working_directory: ~/repo
    #        steps:
    #            - checkout
    deploy:
        machine:
            image: ubuntu-2004:202104-01
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Deploy to Prod
                command: |
                    - ../build/deploy.sh
workflows:
    version: 2
    deploy:
        jobs:
            - deploy
